FROM centos:7

MAINTAINER Gerard Braad <me@gbraad.nl>

ENV GOPATH /workspace
RUN yum install -y curl git gcc golang

COPY . /workspace/src/github.com/gbraad/go-hvkvp
WORKDIR /workspace/src/github.com/gbraad/go-hvkvp

RUN go get -v -d ./...
RUN go test
RUN go install -v ./cmd/hvkvp
